---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---


## Loading and preprocessing the data
```{r}
activity <- read.csv("activity.csv")
activity <-transform(activity, myDate = as.Date(date,"%Y-%m-%d"))
```



## What is mean total number of steps taken per day?
```{r}
steps_by_day <- aggregate(activity$steps, by = list(activity$date), FUN=mean)
mean(steps_by_day$x, na.rm =TRUE)
median(steps_by_day$x, na.rm =TRUE)
```



## What is the average daily activity pattern?
```{r}
steps_interval <- aggregate(steps~interval, data = activity, mean)
library(ggplot2)
qplot(steps_interval$interval,steps_interval$steps,  geom=c("line"))
```


## Imputing missing values
```{r}
count_step_NAs <- sum(is.na(activity$steps))
count_step_NAs
count_interval_NAs <- sum(is.na(activity$interval))
count_interval_NAs 
count_date_NAs <- sum(is.na(activity$date))
count_date_NAs
fixed_activity <- transform(activity, meansteps = subset(steps_interval, interval==interval,steps))
step_NAs <- is.na(activity$steps)
fixed_activity$steps[step_NAs] <- fixed_activity$steps.1[step_NAs]
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
weekd <- weekdays(fixed_activity$myDate,abbreviate=T)
fixed_activity <- transform(fixed_activity, day = ifelse(weekd %in% c("So","Sa"),"Weekend", "Weekday"))
steps_interval_weekday <- aggregate(steps~interval, data = subset(fixed_activity,day=="Weekday"), mean)
qplot(steps_interval_weekday$interval,steps_interval_weekday$steps,  geom=c("line"))
steps_interval_weekend <- aggregate(steps~interval, data = subset(fixed_activity,day=="Weekend"), mean)
qplot(steps_interval_weekend$interval,steps_interval_weekend$steps,  geom=c("line"))
```